version: 0.0
os: linux
files:
  - source: maven-web-application.war
    destination: /opt
hooks:
  BeforeInstall:
    - location: tomcat_install.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: copy_app.sh
      timeout: 180
      runas: root
