version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp dist/* s3://test-bucket-gln
artifacts:
  files:
    - '**/*'
