version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp dist/* s3://test-bucket-gln --recursive --acl public-read --cache-control "max-age=${CACHE_CONTROL}"
artifacts:
  files:
    - '**/*'
